const fonts = [
  { name: "Arial", value: "Arial" },
  { name: "Verdana", value: "Verdana" },
  { name: "Helvetica", value: "Helvetica" },
  { name: "Tahoma", value: "Tahoma" },
  { name: "Trebuchet MS", value: "Trebuchet MS" },
  { name: "Times New Roman", value: "Times New Roman" },
  { name: "Georgia", value: "Georgia" },
  { name: "Garamond", value: "Garamond" },
  { name: "Courier New", value: "Courier New" },
  { name: "Lucida Console", value: "Lucida Console" },
  { name: "Palatino Linotype", value: "Palatino Linotype" },
  { name: "Book Antiqua", value: "Book Antiqua" },
  { name: "Impact", value: "Impact" },
  { name: "Franklin Gothic Medium", value: "Franklin Gothic Medium" },
  { name: "Segoe UI", value: "Segoe UI" },
  { name: "Calibri", value: "Calibri" },
  { name: "Cambria", value: "Cambria" },
  { name: "Constantia", value: "Constantia" },
  { name: "Consolas", value: "Consolas" },
  { name: "Monaco", value: "Monaco" },
  { name: "Futura", value: "Futura" },
  { name: "Rockwell", value: "Rockwell" },
  { name: "Gill Sans", value: "Gill Sans" },
  { name: "Didot", value: "Didot" },
  { name: "Baskerville", value: "Baskerville" },
  { name: "Copperplate", value: "Copperplate" },
  { name: "Brush Script MT", value: "Brush Script MT" },
  { name: "Lucida Sans", value: "Lucida Sans" },
  { name: "Century Gothic", value: "Century Gothic" },
  { name: "Candara", value: "Candara" },
  { name: "Perpetua", value: "Perpetua" },
  { name: "Segoe Print", value: "Segoe Print" },
  { name: "Comic Sans MS", value: "Comic Sans MS" }
];

export default fonts;
