import WeddingImage from "./assets/images/wedding.png";
import WeddingImage2 from "./assets/images/wedding2.avif";
export const templates = [
  {
    id: 1,
    name: "Gold orchids",
    backgroundImage: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    backgroundColor: "bg-cyan-300",
    thumbnail: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    categorie: "wedding",
    term: "trending",
    orientation: "portait",
    theme: "ai",
    price: "free",
    shapes: [
      {
        id: "greeting",
        type: "text",
        x: 141,
        y: 159,
        text: "Togetter with their families",
        fontSize: 30,
        fill: "rgb(143,134,123)",
        isBold: false,
        isItalic: true,
        textAlign: "right",
        fontFamily: "cambria",
      },
      {
        id: "names",
        type: "text",
        x: 228,
        y: 202,
        text: "Aarav & Anaya",
        fontSize: 25,
        fill: "rgb(143,134,123)",
        isBold: true,
        isItalic: true,
        textAlign: "right",
        fontFamily: "arial",
      },
    ],
  },
  {
    id: 2,
    name: "Nocturnal flowers",
    backgroundImage: WeddingImage2,
    backgroundColor: "bg-green-300",
    thumbnail: WeddingImage2,
    categorie: "wedding",
    term: "trending",
    orientation: "portait",
    theme: "elegant",
    price: "free",
    shapes: [
      {
        id: "greeting",
        type: "text",
        x: 200,
        y: 250,
        text: "You're Invited!",
        fontSize: 50,
        fill: "white",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "nunito",
      },
      {
        id: "names",
        type: "text",
        x: 100,
        y: 150,
        text: "Aarav & Anaya",
        fontSize: 26,
        fill: "#fcd34d",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "roboto",
      },
    ],
  },
   {
    id: 3,
    name: "Elegant Wedding Invite",
    backgroundImage: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    backgroundColor: "bg-cyan-300",
    thumbnail: WeddingImage,
    categorie: "wedding",
    term: "trending",
    orientation: "portait",
    theme: "elegant",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 170,   
        y: 250,   
        text: "You're Invited!",
        fontSize: 44,
        fill: "#5D4037",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "weddingText",
        type: "text",
        x: 144,
        y: 360,
        text: "Join us to celebrate the wedding of",
        fontSize: 24,
        fill: "#6D4C41",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Cambria",
      },
      {
        id: "names",
        type: "text",
        x: 200,
        y: 438,
        text: "Aarav & Anaya",
        fontSize: 32,
        fill: "#8D6E63",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
      {
        id: "date",
        type: "text",
        x: 190,
        y: 520,
        text: "Saturday, 25th December 2025",
        fontSize: 20,
        fill: "#6D4C41",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Times New Roman",
      }]
}]
