import WeddingImage from "./assets/images/wedding.png";
import WeddingImage2 from "./assets/images/wedding2.avif";
export const templates = [
  {
    id: 1,
    name: "Gold orchids",
    backgroundImage: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    backgroundColor: "bg-cyan-300",
    thumbnail: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    categorie: "wedding",
    term: "trending",
    orientation: "portait",
    theme: "ai",
    price: "free",
    shapes: [
      {
        id: "greeting",
        type: "text",
        x: 141,
        y: 159,
        text: "Togetter with their families",
        fontSize: 30,
        fill: "rgb(143,134,123)",
        isBold: false,
        isItalic: true,
        textAlign: "right",
        fontFamily: "cambria",
      },
      {
        id: "names",
        type: "text",
        x: 228,
        y: 202,
        text: "Aarav & Anaya",
        fontSize: 25,
        fill: "rgb(143,134,123)",
        isBold: true,
        isItalic: true,
        textAlign: "right",
        fontFamily: "arial",
      },
    ],
  },
  {
    id: 2,
    name: "Nocturnal flowers",
    backgroundImage: WeddingImage2,
    backgroundColor: "bg-green-300",
    thumbnail: WeddingImage2,
    categorie: "wedding",
    term: "trending",
    orientation: "portait",
    theme: "elegant",
    price: "free",
    shapes: [
      {
        id: "greeting",
        type: "text",
        x: 200,
        y: 250,
        text: "You're Invited!",
        fontSize: 50,
        fill: "white",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "nunito",
      },
      {
        id: "names",
        type: "text",
        x: 100,
        y: 150,
        text: "Aarav & Anaya",
        fontSize: 26,
        fill: "#fcd34d",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "roboto",
      },
    ],
  },
   {
    id: 3,
    name: "Elegant Wedding Invite",
    backgroundImage: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    backgroundColor: "bg-cyan-300",
    thumbnail: WeddingImage,
    categorie: "wedding",
    term: "trending",
    orientation: "portait",
    theme: "elegant",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 170,   
        y: 250,   
        text: "You're Invited!",
        fontSize: 44,
        fill: "#5D4037",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "weddingText",
        type: "text",
        x: 144,
        y: 360,
        text: "Join us to celebrate the wedding of",
        fontSize: 24,
        fill: "#6D4C41",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Cambria",
      },
      {
        id: "names",
        type: "text",
        x: 200,
        y: 438,
        text: "Aarav & Anaya",
        fontSize: 32,
        fill: "#8D6E63",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
      {
        id: "date",
        type: "text",
        x: 190,
        y: 520,
        text: "Saturday, 25th December 2025",
        fontSize: 20,
        fill: "#6D4C41",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Times New Roman",
      }]
},
  {
    id: 4,
    name: "Royal Gold Elegance",
    backgroundImage: "https://i.pinimg.com/736x/0c/37/69/0c3769fc4f8f44b8cf3ff773c481a07a.jpg",
    backgroundColor: "bg-amber-200",
    thumbnail: "https://i.pinimg.com/736x/0c/37/69/0c3769fc4f8f44b8cf3ff773c481a07a.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "royal",
    price: "premium",
    shapes: [
      {
        id: "title",
        type: "text",
        x: 220,
        y: 180,
        text: "Wedding Invitation",
        fontSize: 38,
        fill: "#D4AF37",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Playfair Display",
      },
      {
        id: "names",
        type: "text",
        x: 200,
        y: 350,
        text: "Rajesh & Priya",
        fontSize: 48,
        fill: "#8B4513",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Great Vibes",
      }
    ]
  },
  {
    id: 5,
    name: "Floral Paradise",
    backgroundImage: "https://i.pinimg.com/736x/d5/6c/51/d56c51c8e1a3b8b5c9e7e8f9a1b2c3d4.jpg",
    backgroundColor: "bg-pink-100",
    thumbnail: "https://i.pinimg.com/736x/d5/6c/51/d56c51c8e1a3b8b5c9e7e8f9a1b2c3d4.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "floral",
    price: "premium",
    shapes: [
      {
        id: "greeting",
        type: "text",
        x: 180,
        y: 200,
        text: "Save The Date",
        fontSize: 42,
        fill: "#C71585",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Sacramento",
      }
    ]
  },
  {
    id: 6,
    name: "Midnight Romance",
    backgroundImage: "https://i.pinimg.com/736x/1a/2b/3c/1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d.jpg",
    backgroundColor: "bg-slate-900",
    thumbnail: "https://i.pinimg.com/736x/1a/2b/3c/1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "modern",
    price: "premium",
    shapes: [
      {
        id: "couple",
        type: "text",
        x: 180,
        y: 300,
        text: "Together Forever",
        fontSize: 44,
        fill: "#FFD700",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Cinzel",
      }
    ]
  },
  {
    id: 7,
    name: "Peach Blossom Dream",
    backgroundImage: "https://i.pinimg.com/736x/8e/9f/0a/8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b.jpg",
    backgroundColor: "bg-orange-100",
    thumbnail: "https://i.pinimg.com/736x/8e/9f/0a/8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "vintage",
    price: "premium",
    shapes: [
      {
        id: "header",
        type: "text",
        x: 160,
        y: 220,
        text: "Joyfully Invites You",
        fontSize: 36,
        fill: "#FF6347",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Dancing Script",
      }
    ]
  },
  {
    id: 8,
    name: "Emerald Garden",
    backgroundImage: "https://i.pinimg.com/736x/f1/e2/d3/f1e2d3c4b5a69788970605040302010a.jpg",
    backgroundColor: "bg-emerald-200",
    thumbnail: "https://i.pinimg.com/736x/f1/e2/d3/f1e2d3c4b5a69788970605040302010a.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "nature",
    price: "premium",
    shapes: [
      {
        id: "title",
        type: "text",
        x: 190,
        y: 260,
        text: "Celebration of Love",
        fontSize: 40,
        fill: "#2F4F4F",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Lora",
      }
    ]
  },
  {
    id: 9,
    name: "Crystal Luxury",
    backgroundImage: "https://i.pinimg.com/736x/5d/4c/3b/5d4c3b2a19080706050403020100feda.jpg",
    backgroundColor: "bg-cyan-50",
    thumbnail: "https://i.pinimg.com/736x/5d/4c/3b/5d4c3b2a19080706050403020100feda.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "luxury",
    price: "premium",
    shapes: [
      {
        id: "main",
        type: "text",
        x: 170,
        y: 280,
        text: "With This Ring",
        fontSize: 46,
        fill: "#00CED1",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Cormorant Garamond",
      }
    ]
  },
  {
    id: 10,
    name: "Sunset Romance",
    backgroundImage: "https://i.pinimg.com/736x/a9/b8/c7/a9b8c7d6e5f40312233445566778899a.jpg",
    backgroundColor: "bg-rose-200",
    thumbnail: "https://i.pinimg.com/736x/a9/b8/c7/a9b8c7d6e5f40312233445566778899a.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "romantic",
    price: "premium",
    shapes: [
      {
        id: "intro",
        type: "text",
        x: 200,
        y: 320,
        text: "Our Beginning",
        fontSize: 50,
        fill: "#FF69B4",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Parisienne",
      }
    ]
  },
  {
    id: 11,
    name: "Lavender Dreams",
    backgroundImage: "https://i.pinimg.com/736x/2c/3d/4e/2c3d4e5f607182930a4b5c6d7e8f9ab0.jpg",
    backgroundColor: "bg-purple-100",
    thumbnail: "https://i.pinimg.com/736x/2c/3d/4e/2c3d4e5f607182930a4b5c6d7e8f9ab0.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "elegant",
    price: "premium",
    shapes: [
      {
        id: "announcement",
        type: "text",
        x: 175,
        y: 240,
        text: "Two Hearts, One Love",
        fontSize: 38,
        fill: "#9370DB",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Satisfy",
      }
    ]
  },
  {
    id: 12,
    name: "Ivory Sophistication",
    backgroundImage: "https://i.pinimg.com/736x/7a/8b/9c/7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d.jpg",
    backgroundColor: "bg-stone-100",
    thumbnail: "https://i.pinimg.com/736x/7a/8b/9c/7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "classic",
    price: "premium",
    shapes: [
      {
        id: "invitation",
        type: "text",
        x: 185,
        y: 300,
        text: "A Love Story Begins",
        fontSize: 42,
        fill: "#8B7355",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Merriweather",
      }
    ]
  },
  {
    id: 13,
    name: "Tropical Paradise",
    backgroundImage: "https://i.pinimg.com/736x/e4/f5/06/e4f5061728394a5b6c7d8e9f0a1b2c3d.jpg",
    backgroundColor: "bg-teal-100",
    thumbnail: "https://i.pinimg.com/736x/e4/f5/06/e4f5061728394a5b6c7d8e9f0a1b2c3d.jpg",
    categorie: "wedding",
    term: "premium",
    orientation: "portrait",
    theme: "beach",
    price: "premium",
    shapes: [
      {
        id: "welcome",
        type: "text",
        x: 195,
        y: 270,
        text: "Beach Wedding Bliss",
        fontSize: 40,
        fill: "#008080",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Quicksand",
      }
    ]
  }
]
