import WeddingImage from "./assets/images/wedding1.avif";
import WeddingImage2 from "./assets/images/wedding2.avif";
export const templates = [
  {
    id: 1,
    name: "Gold orchids",
    backgroundImage: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    backgroundColor: "bg-cyan-300",
    thumbnail: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "ai",
    price: "free",
    shapes: [
      {
        id: "greeting",
        type: "text",
        x: 141,
        y: 159,
        text: "Together with their families",
        fontSize: 30,
        fill: "rgb(143,134,123)",
        isBold: false,
        isItalic: true,
        textAlign: "right",
        fontFamily: "cambria",
      },
      {
        id: "names",
        type: "text",
        x: 228,
        y: 202,
        text: "Aarav & Anaya",
        fontSize: 25,
        fill: "rgb(143,134,123)",
        isBold: true,
        isItalic: true,
        textAlign: "right",
        fontFamily: "arial",
      },
    ],
  },
   {
    id: 2,
    name: "Elegant Wedding Invite",
    backgroundImage: "https://img.pikbest.com/back_our/bg/20200821/bg/ffb8d44cd3da6_396837.jpg!sw800",
    backgroundColor: "bg-cyan-300",
    thumbnail: WeddingImage,
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "elegant",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 170,   
        y: 250,   
        text: "You're Invited!",
        fontSize: 44,
        fill: "#5D4037",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "weddingText",
        type: "text",
        x: 144,
        y: 360,
        text: "Join us to celebrate the wedding of",
        fontSize: 24,
        fill: "#6D4C41",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Cambria",
      },
      {
        id: "names",
        type: "text",
        x: 200,
        y: 438,
        text: "Aarav & Anaya",
        fontSize: 32,
        fill: "#8D6E63",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
      {
        id: "date",
        type: "text",
        x: 190,
        y: 520,
        text: "Saturday, 25th December 2025",
        fontSize: 20,
        fill: "#6D4C41",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Times New Roman",
      }]
},
  {
    id: 3,
    name: "Romantic Rose",
    backgroundImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800",
    backgroundColor: "bg-rose-100",
    thumbnail: "https://images.unsplash.com/photo-1519741497674-611481863552?w=400",
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "romantic",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 180,
        y: 200,
        text: "Save the Date",
        fontSize: 42,
        fill: "#9F1239",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 200,
        y: 300,
        text: "Emma & James",
        fontSize: 36,
        fill: "#BE185D",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "date",
        type: "text",
        x: 220,
        y: 400,
        text: "June 15, 2026",
        fontSize: 24,
        fill: "#9F1239",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
    ],
  },
  {
    id: 4,
    name: "Classic Minimalist",
    backgroundImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
    backgroundColor: "bg-gray-50",
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "minimalist",
    price: "free",
    shapes: [
      {
        id: "line1",
        type: "line",
        points: [100, 180, 520, 180],
        stroke: "#374151",
        strokeWidth: 1,
      },
      {
        id: "heading",
        type: "text",
        x: 180,
        y: 220,
        text: "WEDDING INVITATION",
        fontSize: 28,
        fill: "#1F2937",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
      {
        id: "names",
        type: "text",
        x: 210,
        y: 320,
        text: "Sarah & Michael",
        fontSize: 38,
        fill: "#111827",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "line2",
        type: "line",
        points: [100, 420, 520, 420],
        stroke: "#374151",
        strokeWidth: 1,
      },
    ],
  },
  {
    id: 5,
    name: "Floral Garden",
    backgroundImage: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800",
    backgroundColor: "bg-green-50",
    thumbnail: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=400",
    categorie: "wedding",
    term: "popular",
    orientation: "portrait",
    theme: "floral",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 150,
        y: 180,
        text: "Together With Their Families",
        fontSize: 22,
        fill: "#166534",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 180,
        y: 280,
        text: "Olivia & William",
        fontSize: 40,
        fill: "#14532D",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "invite",
        type: "text",
        x: 150,
        y: 380,
        text: "Request the pleasure of your company",
        fontSize: 20,
        fill: "#166534",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
    ],
  },
  {
    id: 6,
    name: "Royal Navy",
    backgroundImage: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    backgroundColor: "bg-blue-900",
    thumbnail: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400",
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "elegant",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 200,
        y: 200,
        text: "You Are Invited",
        fontSize: 36,
        fill: "#FCD34D",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 180,
        y: 300,
        text: "Charlotte & Henry",
        fontSize: 38,
        fill: "#FFFFFF",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "date",
        type: "text",
        x: 220,
        y: 400,
        text: "March 20, 2026",
        fontSize: 24,
        fill: "#FCD34D",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
    ],
  },
  {
    id: 7,
    name: "Rustic Charm",
    backgroundImage: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800",
    backgroundColor: "bg-amber-50",
    thumbnail: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=400",
    categorie: "wedding",
    term: "popular",
    orientation: "portrait",
    theme: "rustic",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 200,
        y: 180,
        text: "Join Us",
        fontSize: 48,
        fill: "#78350F",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "subtitle",
        type: "text",
        x: 140,
        y: 260,
        text: "for the wedding celebration of",
        fontSize: 22,
        fill: "#92400E",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 180,
        y: 340,
        text: "Grace & Noah",
        fontSize: 40,
        fill: "#78350F",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
    ],
  },
  {
    id: 8,
    name: "Lavender Dreams",
    backgroundImage: "https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=800",
    backgroundColor: "bg-purple-100",
    thumbnail: "https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=400",
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "romantic",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 180,
        y: 200,
        text: "We're Getting Married!",
        fontSize: 32,
        fill: "#7C3AED",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 200,
        y: 300,
        text: "Sophia & Liam",
        fontSize: 38,
        fill: "#5B21B6",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "date",
        type: "text",
        x: 210,
        y: 400,
        text: "April 10, 2026",
        fontSize: 26,
        fill: "#7C3AED",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
    ],
  },
  {
    id: 9,
    name: "Sunset Beach",
    backgroundImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    backgroundColor: "bg-orange-100",
    thumbnail: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400",
    categorie: "wedding",
    term: "popular",
    orientation: "landscape",
    theme: "beach",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 180,
        y: 180,
        text: "Beach Wedding",
        fontSize: 44,
        fill: "#EA580C",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 200,
        y: 280,
        text: "Mia & Ethan",
        fontSize: 36,
        fill: "#C2410C",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "location",
        type: "text",
        x: 200,
        y: 380,
        text: "Malibu, California",
        fontSize: 22,
        fill: "#EA580C",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
    ],
  },
  {
    id: 10,
    name: "Modern Geometric",
    backgroundImage: "https://images.unsplash.com/photo-1557683316-973673baf926?w=800",
    backgroundColor: "bg-slate-100",
    thumbnail: "https://images.unsplash.com/photo-1557683316-973673baf926?w=400",
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "modern",
    price: "free",
    shapes: [
      {
        id: "rect1",
        type: "rect",
        x: 160,
        y: 150,
        width: 300,
        height: 200,
        fill: "transparent",
        stroke: "#475569",
        strokeWidth: 2,
      },
      {
        id: "heading",
        type: "text",
        x: 220,
        y: 200,
        text: "WE DO",
        fontSize: 52,
        fill: "#1E293B",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
      {
        id: "names",
        type: "text",
        x: 200,
        y: 280,
        text: "Ava & Lucas",
        fontSize: 32,
        fill: "#475569",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
    ],
  },
  {
    id: 11,
    name: "Vintage Lace",
    backgroundImage: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800",
    backgroundColor: "bg-cream-50",
    thumbnail: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=400",
    categorie: "wedding",
    term: "popular",
    orientation: "portrait",
    theme: "vintage",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 140,
        y: 180,
        text: "Together Forever",
        fontSize: 38,
        fill: "#78716C",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 180,
        y: 280,
        text: "Isabella & Mason",
        fontSize: 34,
        fill: "#57534E",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "date",
        type: "text",
        x: 200,
        y: 380,
        text: "September 5, 2026",
        fontSize: 24,
        fill: "#78716C",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
    ],
  },
  {
    id: 12,
    name: "Tropical Paradise",
    backgroundImage: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800",
    backgroundColor: "bg-teal-100",
    thumbnail: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=400",
    categorie: "wedding",
    term: "popular",
    orientation: "portrait",
    theme: "tropical",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 160,
        y: 180,
        text: "Paradise Wedding",
        fontSize: 38,
        fill: "#0D9488",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 180,
        y: 280,
        text: "Luna & Oliver",
        fontSize: 36,
        fill: "#115E59",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "venue",
        type: "text",
        x: 200,
        y: 380,
        text: "Hawaii Islands",
        fontSize: 24,
        fill: "#0D9488",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
    ],
  },
  {
    id: 13,
    name: "Winter Wonderland",
    backgroundImage: "https://images.unsplash.com/photo-1491002052546-bf38f186af56?w=800",
    backgroundColor: "bg-blue-50",
    thumbnail: "https://images.unsplash.com/photo-1491002052546-bf38f186af56?w=400",
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "winter",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 160,
        y: 180,
        text: "Winter Wedding",
        fontSize: 40,
        fill: "#1E40AF",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 180,
        y: 280,
        text: "Aurora & Sebastian",
        fontSize: 32,
        fill: "#1E3A8A",
        isBold: true,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "date",
        type: "text",
        x: 200,
        y: 380,
        text: "December 21, 2026",
        fontSize: 24,
        fill: "#1E40AF",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
    ],
  },
  {
    id: 14,
    name: "Blush Pink",
    backgroundImage: "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=800",
    backgroundColor: "bg-pink-50",
    thumbnail: "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=400",
    categorie: "wedding",
    term: "trending",
    orientation: "portrait",
    theme: "romantic",
    price: "free",
    shapes: [
      {
        id: "heading",
        type: "text",
        x: 180,
        y: 200,
        text: "Forever Begins",
        fontSize: 38,
        fill: "#DB2777",
        isBold: false,
        isItalic: true,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "names",
        type: "text",
        x: 180,
        y: 300,
        text: "Chloe & Benjamin",
        fontSize: 34,
        fill: "#BE185D",
        isBold: true,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Georgia",
      },
      {
        id: "date",
        type: "text",
        x: 220,
        y: 400,
        text: "May 15, 2026",
        fontSize: 24,
        fill: "#DB2777",
        isBold: false,
        isItalic: false,
        textAlign: "center",
        fontFamily: "Arial",
      },
    ],
  },
]
